// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// wiegand_rx2 //
// ----------- //

#define wiegand_rx2_wrap_target 0
#define wiegand_rx2_wrap 19
#define wiegand_rx2_pio_version 0

static const uint16_t wiegand_rx2_program_instructions[] = {
            //     .wrap_target
    0xe020, //  0: set    x, 0
    0xa0c3, //  1: mov    isr, null
    0x4002, //  2: in     pins, 2
    0xa046, //  3: mov    y, isr
    0x0045, //  4: jmp    x--, 5
    0xa2e1, //  5: mov    osr, x                 [2]
    0xa0c3, //  6: mov    isr, null
    0x4002, //  7: in     pins, 2
    0xa026, //  8: mov    x, isr
    0x00ac, //  9: jmp    x != y, 12
    0xa027, // 10: mov    x, osr
    0x0004, // 11: jmp    4
    0xa041, // 12: mov    y, x
    0xa0c3, // 13: mov    isr, null
    0x40fe, // 14: in     osr, 30
    0x4042, // 15: in     y, 2
    0xc010, // 16: irq    nowait 0 rel
    0x8020, // 17: push   block
    0xa027, // 18: mov    x, osr
    0x0004, // 19: jmp    4
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program wiegand_rx2_program = {
    .instructions = wiegand_rx2_program_instructions,
    .length = 20,
    .origin = -1,
    .pio_version = wiegand_rx2_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config wiegand_rx2_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + wiegand_rx2_wrap_target, offset + wiegand_rx2_wrap);
    return c;
}
#endif

